### ISSUE TITLE
FTP exists = false, read gets the file

### ISSUE THREAD

**Issue by lsv** [KnpLabs/Gaufrette#319]
````php
$url = '152/152.pdf';

$this->filesystem = @gaufrette.invoice_filesystem // Symfony service
$this->filesystem->has($url); // FALSE
$this->filesystem->getAdapter()->exists($url); // FALSE
$this->filesystem->getAdapter()->read($url); // Gives me the PDF file
$this->filesystem->get($url); // Exception FileNotFound
````

The file (when I use the read, gets saved nicely in my invoice_local) and the content is correct
But why does the has, exists and get gives me false/exception ?

I also tried add the 152 directory to directory to the FTP configuration, but still the same.

````yaml
knp_gaufrette:
  adapters:
    invoice_ftp:
      ftp:
        host: ftp.localhost
        directory: /upload

    invoice_local:
      safe_local:
        directory: "%kernel.cache_dir%/invoices"

    invoice_cache:
      cache:
        source: invoice_ftp
        cache: invoice_local
        ttl: 7200
  filesystems:
    invoice:
      adapter: invoice_cache
````
