### ISSUE TITLE
[1.0] Openstack error File not found when `setMetadata` and call `resetMetadata`

### ISSUE THREAD

**Issue by chadyred** [KnpLabs/Gaufrette#635]
Hello

@nicolasmure I followed the development of the new OpenStack adapter. I try it on the bundle and I make an issue on it but it seems this errors is link to this package.

I have try to use this branch on KnpGaufretteBundle (by redefining opencloud service for this new one).

```
services:
    knp_gaufrette.adapter.opencloud:
        class: Gaufrette\Adapter\OpenStack
        abstract: true
        arguments: ["first", "second", "third", "fourth"]

    opencloud.connection:
        class: OpenStack\OpenStack
        arguments:
             -
                tokenId: "%openstack_token%"
                region: "%openstack_object_storage_region%"
                authUrl: "%openstack_identity_url%"
                username: "%openstack_username%"
                password: "%openstack_password%"
                tenantName: "%openstack_tenant_name%" # v3 use toeken, v2 user authentication username
                tenantId: "%openstack_tenant_id%"
                debugLog: true
                user: { name: "%openstack_username%", password: "%openstack_password%", domain: { id: 'default', name: 'Default' } }
                scope: { project: { name: "%openstack_project_name%", id: "%openstack_project_id%", domain: { id: 'default', name: 'Default' }} }
```

But an error appear on `setMetadata`, the `resetMetadata` method return a `FileNotFound` on OpenStack 1-x branch for KnpGaufrette.

![image](https://user-images.githubusercontent.com/5954673/76707746-383f1b00-66f2-11ea-8b3b-f439b2f4b12d.png)

If I remove the  `resetMetadata` call all works great !

Like this : https://github.com/KnpLabs/Gaufrette/pull/636
